# Generated by Django 5.2.10 on 2026-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_id_alter_car_id_alter_carimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
